/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.User;

/**
 *
 * @author rutul
 */
public class detailsform extends javax.swing.JPanel {

    /**
     * Creates new form detailsform
     */
    private final JPanel bottompanel;
    public detailsform(JPanel bottompanel) {
        initComponents();
        this.bottompanel = bottompanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        patienttype = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        firstname1 = new javax.swing.JTextField();
        lastname2 = new javax.swing.JTextField();
        age1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        message1 = new javax.swing.JTextField();
        image1 = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();
        patienttype1 = new javax.swing.JComboBox<>();
        gender1 = new javax.swing.JRadioButton();
        gender2 = new javax.swing.JRadioButton();
        firstname5 = new javax.swing.JLabel();
        lastname5 = new javax.swing.JLabel();
        email5 = new javax.swing.JLabel();
        message5 = new javax.swing.JLabel();
        patienttype5 = new javax.swing.JLabel();
        gender5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));

        title.setBackground(new java.awt.Color(0, 255, 204));
        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setText("Pateint Registration Form");

        firstname.setText("First Name");

        lastname.setText("Last Name");

        age.setText("Age");

        email.setText("Email");

        message.setText("Message");

        gender.setText("Gender");

        patienttype.setText("Patient Type");

        image.setText("Image");

        firstname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstname1KeyPressed(evt);
            }
        });

        age1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                age1KeyPressed(evt);
            }
        });

        message1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                message1ActionPerformed(evt);
            }
        });

        image1.setBackground(new java.awt.Color(102, 255, 255));
        image1.setText("Upload");
        image1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image1ActionPerformed(evt);
            }
        });

        submit1.setBackground(new java.awt.Color(255, 102, 102));
        submit1.setText("Submit");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });

        patienttype1.setBackground(new java.awt.Color(102, 255, 255));
        patienttype1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type", "Emergency", "Regular" }));

        buttonGroup.add(gender1);
        gender1.setText("Male");

        buttonGroup.add(gender2);
        gender2.setText("Female");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(patienttype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(age, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(image, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gender1)
                                .addComponent(firstname1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lastname2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(age1)
                                .addComponent(email1)
                                .addComponent(gender2)
                                .addComponent(message1)
                                .addComponent(patienttype1, 0, 105, Short.MAX_VALUE))
                            .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(title))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(submit1)))
                        .addGap(31, 31, 31)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstname5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastname5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(email5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(message5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gender5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patienttype5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname)
                    .addComponent(firstname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname5))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname)
                    .addComponent(lastname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname5))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(age1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email5))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(message)
                            .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(message5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(gender))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(gender5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(gender1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(patienttype)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(patienttype5)
                        .addGap(22, 22, 22)
                        .addComponent(image)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(patienttype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(image1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void message1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_message1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_message1ActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        // TODO add your handling code here:
        User newUser = new User();
        newUser.setFirstname1(firstname1.getText());
        newUser.setLastname1(lastname2.getText());
        newUser.setAge1(age1.getText());
        newUser.setEmail1(email1.getText());
        newUser.setMessage1(message1.getText());
        newUser.setPatienttype1(patienttype1.getSelectedItem().toString());
        newUser.setImage1(image1.getActionCommand());
        
        view newview = new view(newUser);
        CardLayout layout=(CardLayout)bottompanel.getLayout();
        bottompanel.add(newview);
        layout.next(bottompanel);
        
  
        
    }//GEN-LAST:event_submit1ActionPerformed

    private void age1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age1KeyPressed
        // TODO add your handling code here:
        try{
            int age = Integer.parseInt(age1.getText());
            age1.setForeground(Color.black);
        }
        catch(Exception e){
            age1.setForeground(Color.red);
            
        }
    }//GEN-LAST:event_age1KeyPressed

    private void firstname1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstname1KeyPressed
        // TODO add your handling code here:
       // String PATTERN = "^[a-zA-Z]{2,20}$";
        //Pattern pat = Pattern.compile(PATTERN);
        //Matcher match = pat.matcher(firstname5.getText());
        //if(!match.matches()){
          //  firstname5.setText("Please enter Only Alphabets in first name");
        //}
        //else {
          //  firstname5.setText(this.firstname1.getText());
        //}
        try{ 
            String firstname = String.valueOf(firstname1.getText());
            firstname1.setForeground(Color.black);
        }
        catch(Exception e){
            firstname1.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_firstname1KeyPressed

    private void image1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename=null;
        filename = f.getAbsolutePath();
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(filename);
    }//GEN-LAST:event_image1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JTextField age1;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel email5;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField firstname1;
    private javax.swing.JLabel firstname5;
    private javax.swing.JLabel gender;
    private javax.swing.JRadioButton gender1;
    private javax.swing.JRadioButton gender2;
    private javax.swing.JLabel gender5;
    private javax.swing.JLabel image;
    private javax.swing.JButton image1;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lastname2;
    private javax.swing.JLabel lastname5;
    private javax.swing.JLabel message;
    private javax.swing.JTextField message1;
    private javax.swing.JLabel message5;
    private javax.swing.JLabel patienttype;
    private javax.swing.JComboBox<String> patienttype1;
    private javax.swing.JLabel patienttype5;
    private javax.swing.JButton submit1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private static class firstname1TextField {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        }

        public firstname1TextField() {
        }
    }





    }

