/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.User;

/**
 *
 * @author rutul
 */
public class view extends javax.swing.JPanel {

    /**
     * Creates new form view
     */
    private final User newUser;
    public view(User newUser) {
        initComponents();
       
        this.newUser = newUser;
        populateData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        patienttype = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        firstname1 = new javax.swing.JTextField();
        lastname2 = new javax.swing.JTextField();
        age1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        message1 = new javax.swing.JTextField();
        gender1 = new javax.swing.JRadioButton();
        gender2 = new javax.swing.JRadioButton();
        patienttype1 = new javax.swing.JComboBox<>();
        image1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 204));

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setText("Patient Registration View");

        firstname.setText("First Name");

        lastname.setText("Last Name");

        age.setText("Age");

        email.setText("Email");

        message.setText("Message");

        gender.setText("Gender");

        patienttype.setText("Patient Type");

        image.setText("Image");

        firstname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname1ActionPerformed(evt);
            }
        });

        buttonGroup.add(gender1);
        gender1.setText("Male");
        gender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender1ActionPerformed(evt);
            }
        });

        buttonGroup.add(gender2);
        gender2.setText("Female");

        patienttype1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type", "Emergency", "Regular" }));

        image1.setBackground(new java.awt.Color(255, 255, 51));
        image1.setText("Upload");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(age, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lastname, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(firstname)
                            .addGap(265, 265, 265))
                        .addComponent(message, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(image, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(gender)
                    .addComponent(patienttype))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gender1)
                    .addComponent(gender2)
                    .addComponent(message1)
                    .addComponent(email1)
                    .addComponent(age1)
                    .addComponent(lastname2)
                    .addComponent(firstname1)
                    .addComponent(patienttype1, 0, 0, Short.MAX_VALUE)
                    .addComponent(image1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addGap(171, 171, 171))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(title)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname)
                    .addComponent(firstname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname)
                    .addComponent(lastname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(age1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(message)
                    .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(gender)
                        .addGap(34, 34, 34)
                        .addComponent(patienttype)
                        .addGap(26, 26, 26)
                        .addComponent(image))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gender1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patienttype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(image1)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname1ActionPerformed

    private void gender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JTextField age1;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField firstname1;
    private javax.swing.JLabel gender;
    private javax.swing.JRadioButton gender1;
    private javax.swing.JRadioButton gender2;
    private javax.swing.JLabel image;
    private javax.swing.JButton image1;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lastname2;
    private javax.swing.JLabel message;
    private javax.swing.JTextField message1;
    private javax.swing.JLabel patienttype;
    private javax.swing.JComboBox<String> patienttype1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
          firstname1.setText(this.newUser.getFirstname1());
          lastname2.setText(this.newUser.getLastname1());
          age1.setText(this.newUser.getAge1());
          email1.setText(this.newUser.getEmail1());
          message1.setText(this.newUser.getMessage1());
          patienttype1.setSelectedItem(this.newUser.getPatienttype1());
          image1.setActionCommand(this.newUser.getImage1());
          
          
       
    }
}
